# Solución Reto Optimización Estocástica
*Modelo de Optimización para la Reforestación en México:
Distribución de Especies y Simulación de Supervivencia en
polígonos forestales*

Valeria Isabel Sada Chapa - A00837046

Pedro Soto Juárez - A00837560

Leonardo De Regil Cárdenas - A00837118

Diego Armando Mijares Ledezma - A01722421

Alexei Carrillo Acosta - A01285424

In [ ]:
# Librerias.
import numpy as np

# Definición de las especies y sus nombres.
especies = {
    1: "Agave lechuguilla",
    2: "Agave salmiana",
    3: "Agave scabra",
    4: "Agave striata",
    5: "Opuntia cantabrigiensis",
    6: "Opuntia engelmannii",
    7: "Opuntia robusta",
    8: "Opuntia streptacantha",
    9: "Prosopis laevigata",
    10: "Yucca filifera"
}

# Probabilidades de estar en el polígono inicial de cada especie.
probabilidad_especies = {"Agave lechuguilla": 0.009732368,
"Agave salmiana": 0.046575495,
"Agave scabra": 0.010014725,
"Agave striata": 0.009461784,
"Opuntia cantabrigiensis": 0.012244802,
"Opuntia engelmannii": 0.009956236,
"Opuntia robusta": 0.018060235,
"Opuntia streptacantha": 0.015011395,
"Prosopis laevigata": 0.02020418,
"Yucca filifera": 0.006457316}

# Distribución objetivo de especies.
distribucion_especies = {
    "Agave lechuguilla": 42,
    "Agave salmiana": 196,
    "Agave scabra": 42,
    "Agave striata": 42,
    "Opuntia cantabrigiensis": 49,
    "Opuntia engelmannii": 38,
    "Opuntia robusta": 73,
    "Opuntia streptacantha": 64,
    "Prosopis laevigata": 86,
    "Yucca filifera": 26
}

# Matriz de competencia entre especies.
matriz_competencia_especies = np.array([
    [0.65, 0.4, 0.5, 0.6, 0.2, 0.3, 0.3, 0.3, 0.1, 0.4],
    [0.4, 0.65, 0.5, 0.6, 0.2, 0.3, 0.3, 0.3, 0.1, 0.5],
    [0.5, 0.5, 0.3, 0.6, 0.3, 0.3, 0.4, 0.4, 0.1, 0.5],
    [0.6, 0.6, 0.6, 0.3, 0.3, 0.4, 0.4, 0.4, 0.2, 0.6],
    [0.2, 0.2, 0.3, 0.3, 0.1, 0.5, 0.5, 0.5, 0.3, 0.3],
    [0.3, 0.3, 0.3, 0.4, 0.5, 0.1, 0.6, 0.6, 0.3, 0.3],
    [0.3, 0.3, 0.4, 0.4, 0.5, 0.6, 0.3, 0.6, 0.3, 0.3],
    [0.3, 0.3, 0.4, 0.4, 0.5, 0.6, 0.6, 0.1, 0.3, 0.3],
    [0.1, 0.1, 0.1, 0.2, 0.3, 0.3, 0.3, 0.3, 0.65, 0.2],
    [0.4, 0.5, 0.5, 0.6, 0.3, 0.3, 0.3, 0.3, 0.2, 0.3]
])

# Inicializar el polígono con 0s (espacios vacíos).
poligono = np.zeros((47, 14))


# Generar plantas en el polígono vacío en base al histórico de los 30 polígonos.
def genera_plantas_poligono(poligono, probabilidad_especies):

    poligono_antes_de_plantar = poligono

    for r in range(47):
        for c in range(14):
            poligono_antes_de_plantar[r, c] = np.random.choice(np.arange(0, 11), p=[0.842281465, probabilidad_especies["Agave lechuguilla"],
                                            probabilidad_especies["Agave salmiana"], probabilidad_especies["Agave scabra"],
                                            probabilidad_especies["Agave striata"], probabilidad_especies["Opuntia cantabrigiensis"],
                                            probabilidad_especies["Opuntia engelmannii"], probabilidad_especies["Opuntia robusta"],
                                            probabilidad_especies["Opuntia streptacantha"], probabilidad_especies["Prosopis laevigata"],
                                            probabilidad_especies["Yucca filifera"]])

    return poligono_antes_de_plantar

# Calcular vecinos para cada celda del polígono.
def calcula_vecinos(poligono_con_plantas, r, c):
    lista_vecinos = []
    if c == 0:
        if r == 0:
            planta_vecino_este = poligono_con_plantas[r, c + 1]
            planta_vecino_sur = poligono_con_plantas[r + 1, c]
            lista_vecinos.extend([planta_vecino_este, planta_vecino_sur])
        elif r == 46:
            planta_vecino_este = poligono_con_plantas[r, c + 1]
            planta_vecino_norte = poligono_con_plantas[r - 1, c]
            lista_vecinos.extend([planta_vecino_este, planta_vecino_norte])
        else:
            planta_vecino_este = poligono_con_plantas[r, c + 1]
            planta_vecino_norte = poligono_con_plantas[r - 1, c]
            planta_vecino_sur = poligono_con_plantas[r + 1, c]
            lista_vecinos.extend([planta_vecino_este, planta_vecino_norte, planta_vecino_sur])
    elif c == 13:
        if r == 0:
            planta_vecino_oeste = poligono_con_plantas[r, c - 1]
            planta_vecino_sur = poligono_con_plantas[r + 1, c]
            lista_vecinos.extend([planta_vecino_oeste, planta_vecino_sur])
        elif r == 46:
            planta_vecino_norte = poligono_con_plantas[r - 1, c]
            planta_vecino_oeste = poligono_con_plantas[r, c - 1]
            lista_vecinos.extend([planta_vecino_norte, planta_vecino_oeste])
        else:
            planta_vecino_norte = poligono_con_plantas[r - 1, c]
            planta_vecino_oeste = poligono_con_plantas[r, c - 1]
            planta_vecino_sur = poligono_con_plantas[r + 1, c]
            lista_vecinos.extend([planta_vecino_norte, planta_vecino_oeste, planta_vecino_sur])
    elif r == 0:
        planta_vecino_este = poligono_con_plantas[r, c + 1]
        planta_vecino_oeste = poligono_con_plantas[r, c - 1]
        planta_vecino_sur = poligono_con_plantas[r + 1, c]
        lista_vecinos.extend([planta_vecino_este, planta_vecino_oeste, planta_vecino_sur])
    elif r == 46:
        planta_vecino_este = poligono_con_plantas[r, c + 1]
        planta_vecino_oeste = poligono_con_plantas[r, c - 1]
        planta_vecino_norte = poligono_con_plantas[r - 1, c]
        lista_vecinos.extend([planta_vecino_este, planta_vecino_oeste, planta_vecino_norte])
    else:
        planta_vecino_este = poligono_con_plantas[r, c + 1]
        planta_vecino_oeste = poligono_con_plantas[r, c - 1]
        planta_vecino_norte = poligono_con_plantas[r - 1, c]
        planta_vecino_sur = poligono_con_plantas[r + 1, c]
        lista_vecinos.extend([planta_vecino_este, planta_vecino_oeste, planta_vecino_norte, planta_vecino_sur])

    return lista_vecinos

# Plantar en los espacios vacíos minimizando la competencia
def planta_segunda_etapa(poligono_antes_de_plantar, matriz_competencia_especies, distribucion_especies):
    filas = len(poligono_antes_de_plantar)
    columnas = len(poligono_antes_de_plantar[0])
    poligono_con_plantas = poligono_antes_de_plantar.copy()
    conteo_especies_actual = {i: np.sum(poligono_con_plantas == i) for i in range(1, 11)}

    for r in range(filas):
        for c in range(columnas):
            if poligono_con_plantas[r][c] == 0:
                menor_competencia = float('inf')
                mejor_especie = 0

                for especie_num in range(1, 11):
                    if conteo_especies_actual[especie_num] < distribucion_especies[especies[especie_num]]:
                        vecinos = calcula_vecinos(poligono_con_plantas, r, c)
                        competencia = sum([matriz_competencia_especies[especie_num - 1][int(vecino) - 1]
                                           for vecino in vecinos if vecino != 0])

                        if competencia < menor_competencia:
                            menor_competencia = competencia
                            mejor_especie = especie_num

                # Plantar la especie con la menor competencia
                poligono_con_plantas[r][c] = mejor_especie
                conteo_especies_actual[mejor_especie] += 1

    return poligono_con_plantas

# Calcular la competencia total entre vecinos.
def calcula_competencia_total(poligono_con_plantas, matriz_competencia_especies):
    filas = len(poligono_con_plantas)
    columnas = len(poligono_con_plantas[0])
    competencia_total = 0

    for r in range(filas):
        for c in range(columnas):
            if poligono_con_plantas[r, c] != 0:
                vecinos = calcula_vecinos(poligono_con_plantas, r, c)
                competencia = sum([matriz_competencia_especies[int(poligono_con_plantas[r, c]) - 1][int(vecino) - 1]
                                   for vecino in vecinos if vecino != 0])
                competencia_total += competencia

    return competencia_total

# 1000 Iteraciones ######################################################################

num_iteraciones = 1000

total_plantas_inicial = 0
conteo_inicial_por_planta = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0}
conteo_final_por_planta = {1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0}
competencia_promedio = 0

for i in range(num_iteraciones):

    # Generar polígono inicial
    poligono_inicial = genera_plantas_poligono(poligono, probabilidad_especies)
    poligono_final = planta_segunda_etapa(poligono_inicial, matriz_competencia_especies, distribucion_especies)

    # Contar cuántas plantas de cada especie hay antes de plantar
    conteo_inicial_especies = {numero: np.sum(poligono_inicial == numero) for numero in range(1, 11)}

    for numero in range(1,11):
        conteo_inicial_por_planta[numero] += conteo_inicial_especies[numero]

    total_plantas_inicial = total_plantas_inicial + sum(conteo_inicial_especies.values())

    # Contar cuántas plantas de cada especie hay después de plantar
    conteo_final_especies = {numero: np.sum(poligono_final == numero) for numero in range(1, 11)}

    for numero in range(1,11):
        conteo_final_por_planta[numero] += conteo_final_especies[numero]

    # Calcular la diferencia en el número de plantas de cada especie
    diferencia_especies = {numero: conteo_final_especies[numero] - conteo_inicial_especies[numero] for numero in range(1, 11)}

    competencia_total = calcula_competencia_total(poligono_final, matriz_competencia_especies)

    competencia_promedio += competencia_total

print()
print("Ultima Iteración")
print("---------------------------------------------------------------------------")
print("Polígono Inicial:")
print(poligono_inicial)

print()
print("Polígono Final:")
print(poligono_final)
print("---------------------------------------------------------------------------")

# Resultados ############################################################################

promedio_plantas_iniciales = total_plantas_inicial/num_iteraciones

promedios_iniciales_por_planta = {numero: (conteo / num_iteraciones) for numero, conteo in conteo_inicial_por_planta.items()}

promedios_finales_por_planta = {numero: (conteo / num_iteraciones) for numero, conteo in conteo_final_por_planta.items()}

promedio_competencia_plantas = ((competencia_promedio/num_iteraciones)/25.1)

print()
print("-- Métricas --")
print()
print("Promedio Inicial por Planta:")
for nombre, numero in promedios_iniciales_por_planta.items():
    print(f"{nombre}: {round(numero)}")

print()
print("Promedio Final por Planta:")
for nombre, numero in promedios_finales_por_planta.items():
    print(f"{nombre}: {round(numero)}")

print()
print(f"Promedio Inicial de Plantas Total: {round(promedio_plantas_iniciales)}")

print()
print(f"Promedio de Competencia entre Plantas: {round(promedio_competencia_plantas)}%")

print()
print("Cantidad Promedio de Plantas a Comprar:")
for nombre, numero in promedios_iniciales_por_planta.items():
    print(f"{nombre}: {distribucion_especies[especies[nombre]] - round(numero)}")




Ultima Iteración
---------------------------------------------------------------------------
Polígono Inicial:
[[ 0.  9.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  4.  0.  0.  0.  0.  6.  0.  3.  0.  0.]
 [ 0.  0.  6.  5. 10.  0.  0. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  7.  0.  0.  0.  0.  0.  0. 10.]
 [ 0.  0.  0.  2.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  7.  0.  0.  0.  0.  0.  7.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0.  0.  0.  0.  0.  9.  0.  0.  9.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  9.  0.  0.  0.  0.  0.  0.  0.  0.  0.  8.]
 [ 0.  0.  0.  0.  0.  2.  2.  0.  0.  0.  0.  0.  0.  8.]
 [ 0.  3.  0.  0.  0.  0.  0.  0.  7.  0.  0.  0.  0.  0.]
 [ 0.  0.  2.  0.  0.  0.  0.  9.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  9.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  2.  0.  0.]
 [ 

In [ ]:
# Matriz de Transición.
matriz_competencia_normalizada = matriz_competencia_especies / matriz_competencia_especies.sum(axis=1, keepdims=True)

probabilidad_plantacion = np.array(list(probabilidad_especies.values()))
matriz_transicion = probabilidad_plantacion[:, None] * matriz_competencia_normalizada

matriz_transicion_final = matriz_transicion / matriz_transicion.sum(axis=1, keepdims=True)

print(pd.DataFrame(matriz_transicion_final))

          0         1         2         3         4         5         6  \
0  0.173333  0.106667  0.133333  0.160000  0.053333  0.080000  0.080000   
1  0.103896  0.168831  0.129870  0.155844  0.051948  0.077922  0.077922   
2  0.128205  0.128205  0.076923  0.153846  0.076923  0.076923  0.102564   
3  0.136364  0.136364  0.136364  0.068182  0.068182  0.090909  0.090909   
4  0.062500  0.062500  0.093750  0.093750  0.031250  0.156250  0.156250   
5  0.081081  0.081081  0.081081  0.108108  0.135135  0.027027  0.162162   
6  0.075000  0.075000  0.100000  0.100000  0.125000  0.150000  0.075000   
7  0.078947  0.078947  0.105263  0.105263  0.131579  0.157895  0.157895   
8  0.039216  0.039216  0.039216  0.078431  0.117647  0.117647  0.117647   
9  0.108108  0.135135  0.135135  0.162162  0.081081  0.081081  0.081081   

          7         8         9  
0  0.080000  0.026667  0.106667  
1  0.077922  0.025974  0.129870  
2  0.102564  0.025641  0.128205  
3  0.090909  0.045455  0.136364  
4  0